In [63]:
import matplotlib.pyplot as plt
import numpy as np
import os

def plot_pixel_correlation(img_array, direction, filename, folder_path):
    # 计算并绘制相关性散点图
    if direction == 'horizontal':
        original = img_array[:, :-1].flatten()
        shifted = img_array[:, 1:].flatten()
    elif direction == 'vertical':
        original = img_array[:-1, :].flatten()
        shifted = img_array[1:, :].flatten()
    elif direction == 'diagonal':
        original = img_array[:-1, :-1].flatten()
        shifted = img_array[1:, 1:].flatten()

 
    plt.figure()
    plt.scatter(original, shifted, alpha=0.5, s=0.5)  # s 控制点的大小，alpha 控制点的透明度
    plt.title(f'{direction.capitalize()} Pixel Correlation')
    plt.xlabel('Pixel Value at Position (n)')
    plt.ylabel('Pixel Value at Position (n+1)')
    plt.grid(True)  # 添加网格线
    plt.xlim([0, 255])
    plt.ylim([0, 255])
    # 保存图像
    analysis_filename = f'{direction}_correlation_{filename}.png'
    plt.savefig(os.path.join(folder_path, analysis_filename))
    plt.close()

import numpy as np
from PIL import Image

# 创建一个示例图像数组

# 设置文件名和保存路径
folder_path = './correlation_plots'
file_name1 = 'test3.png'


image1 = Image.open(folder_path + '\\' + file_name1)


# 将图像转换为 NumPy 数组
img_array1 = np.asarray(image1)

# 确保保存路径存在
os.makedirs(folder_path, exist_ok=True)

h1 = plot_pixel_correlation(img_array1, 'horizontal', file_name1, folder_path)
v1 = plot_pixel_correlation(img_array1, 'vertical', file_name1, folder_path)
d1 = plot_pixel_correlation(img_array1, 'diagonal', file_name1, folder_path)


# pad_width = len(h1[1]) - len(d1[1])
# padding_d1 = np.pad(d1, ((0,0),(0, pad_width)),'constant',constant_values = 0)
# # print(padding_d1.shape)
# # print(h1.shape)

# h2 = plot_pixel_correlation(img_array2, 'horizontal', file_name2, folder_path)
# v2 = plot_pixel_correlation(img_array2, 'vertical', file_name2, folder_path)
# d2 = plot_pixel_correlation(img_array2, 'diagonal', file_name2, folder_path)
# pad_width = len(h2[1]) - len(d2[1])
# padding_d2 = np.pad(d2, ((0,0),(0, pad_width)),'constant',constant_values = 0)


# pc1 = np.vstack((h1,v1,padding_d1))
# pc2 = np.vstack((h2,v2,padding_d2))

# print(pc1.shape)
# print



In [55]:
import torch.nn as nn
import torch

pc1 = torch.tensor(pc1).clone().detach()
pc2 = torch.tensor(pc2).clone().detach()

MSE_loss = nn.MSELoss()
loss = MSE_loss(pc1.float(), pc2.float())
loss.item()


C:\Users\崔庆轩喜欢摆\AppData\Local\Temp\ipykernel_19292\3449724755.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  pc1 = torch.tensor(pc1).clone().detach()
C:\Users\崔庆轩喜欢摆\AppData\Local\Temp\ipykernel_19292\3449724755.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  pc2 = torch.tensor(pc2).clone().detach()


4116.732421875

In [57]:
import matplotlib.pyplot as plt
import numpy as np
import os
import torch

def pixel_correlation(img_array):

    h_original = img_array[:, :-1].flatten()
    h_shifted = img_array[:, 1:].flatten()

    v_original = img_array[:-1, :].flatten()
    v_shifted = img_array[1:, :].flatten()

    d_original = img_array[:-1, :-1].flatten()
    d_shifted = img_array[1:, 1:].flatten()


    h = np.vstack((h_original,h_shifted))
    d = np.vstack((d_original,d_shifted))
    v = np.vstack((v_original,v_shifted))

    pad_width = len(h[1]) - len(d[1])
    padding_d = np.pad(d, ((0,0),(0, pad_width)),'constant',constant_values = 0)      

    pixel_corrlation = np.vstack((h,v,padding_d))
    pixel_corrlation = torch.tensor(pixel_corrlation)
    return pixel_corrlation.clone().detach()

pc1 = pixel_correlation(img_array1)
pc2 = pixel_correlation(img_array2)

loss = MSE_loss(pc1.float(), pc2.float())
loss.item()

4116.732421875

In [62]:
print(img_array1.shape)
print(img_array1)

(369, 369, 4)
[[[ 28  28  28 255]
  [ 24  24  24 255]
  [ 21  21  21 255]
  ...
  [ 18  18  18 255]
  [ 22  22  22 255]
  [ 23  23  23 255]]

 [[ 22  22  22 255]
  [ 21  21  21 255]
  [ 20  20  20 255]
  ...
  [ 15  15  15 255]
  [ 18  18  18 255]
  [ 16  16  16 255]]

 [[ 22  22  22 255]
  [ 18  18  18 255]
  [ 15  15  15 255]
  ...
  [ 19  19  19 255]
  [ 10  10  10 255]
  [ 12  12  12 255]]

 ...

 [[ 22  22  22 255]
  [ 17  17  17 255]
  [ 13  13  13 255]
  ...
  [  9   9   9 255]
  [ 15  15  15 255]
  [ 18  18  18 255]]

 [[ 28  28  28 255]
  [ 21  21  21 255]
  [ 15  15  15 255]
  ...
  [ 11  11  11 255]
  [ 17  17  17 255]
  [ 23  23  23 255]]

 [[ 35  35  35 255]
  [ 25  25  25 255]
  [ 16  16  16 255]
  ...
  [ 15  15  15 255]
  [ 19  19  19 255]
  [ 26  26  26 255]]]
